- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
    - name: update repositories
      dnf: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages.yml
    - include: tasks/zsh-setup.yml
