- name: Install nodejs and npm
  dnf:
    name: ["nodejs", "npm"]
  tags:
    - install
    - node
- name: Install N
  npm:
    name: n
    global: yes
  tags:
    - install
    - node
- name: Install correct version of Node
  shell: n 14
  tags:
    - install
    - node
